version: '3.8'

services:
  app:
    build: .
    container_name: rag_app
    ports:
      - "7860:7860"
    volumes:
      - ./${VECTOR_DB_PATH}:/app/${VECTOR_DB_PATH}
      - ./chat_history:/app/chat_history
      - ./docs:/app/docs
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama
    container_name: ollama_server
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data:
